import fs from 'fs';
import path from 'path';

// Complete dictionary of all 28 States + 8 Union Territories with all their districts and major sub-districts/tehsils/villages
const INDIA_DATA = {
  "Uttar Pradesh (उत्तर प्रदेश)": {
    "Ghaziabad (गाजियाबाद)": ["Kalchina (कलछीना)", "Nigrawathi (निगरावठी)", "Samaypur (समयपुर)", "Akalpur (अकलपुर)", "Nurpur (नूरपुर)", "Barayla (बरैला)", "Mindori (मिंडोरी)", "Nindori (निंदोरी)", "Nahal (नाहल)", "Dasna (डासना)", "Loni (लोणी)", "Modinagar (मोदीनगर)", "Muradnagar (मुरादनगर)", "Bhojpur (भोजपुर)", "Razapur (रजापुर)", "Farrukhnagar (फर्रुखनगर)", "Duhai (दुहाई)", "Sikrod (सकरोड़)", "Morta (मोर्ता)", "Morti (मोर्ती)", "Jalalabad (जलालाबाद)", "Khindora (खिंदोरा)", "Shahpur (शाहपुर)", "Govindpuri (गोविंदपुरी)"],
    "Meerut (मेरठ)": ["Mawana (मवाना)", "Sardhana (सरधना)", "Hastinapur (हस्तिनापुर)", "Parikshitgarh (परीक्षितगढ़)", "Daurala (दौराला)", "Kithore (किठौर)", "Janakpuri (जनकपुरी)", "Lawar (नावड़)", "Rohata (रोहटा)", "Jani Khurd (जानी खुर्द)", "Machhra (माछरा)"],
    "Bulandshahr (बुलंदशहर)": ["Sikandrabad (सिकंदराबाद)", "Anupshahr (अनूपशहर)", "Khurja (खुरजा)", "Gulaothi (गुनावठी)", "Jahangirabad (जहांगीराबाद)", "Pahasu (पहासू)", "Chhatari (छतारी)", "Siana (स्याना)", "Shikarpur (शिकारपुर)", "Dibai (डिबाई)", "Danpur (दानपुर)"],
    "Gautam Buddha Nagar (नोएडा / ग्रेटर नोएडा)": ["Dadri (दादरी)", "Jewar (जेवर)", "Dankaur (दनकौर)", "Rabupura (रबुपुरा)", "Bilaspur (बिलासपुर)", "Bhangel (भंगेल)", "Surajpur (सूरजपुर)", "Bisrakh (बिसरख)", "Chhapraula (छपरौला)"],
    "Hapur (हापुड़)": ["Garhmukteshwar (गढ़मुक्तेश्वर)", "Dhaulana (धौलाना)", "Babu Garh (बाबूगढ़)", "Pilkhuwa (पिलखुवा)", "Simbhawali (सिंभावली)", "Kharakpur (खरकपुर)"],
    "Baghpat (बागपत)": ["Baraut (बड़ौत)", "Khekra (खेखड़ा)", "Binauli (बिनौली)", "Chhaprauli (छपरौली)", "Pilana (पिलाना)", "Agarwal Mandi (अग्रवाल मंडी)"],
    "Muzaffarnagar (मुजफ्फरनगर)": ["Budhana (बुढ़ाना)", "Khatauli (खतौली)", "Jansath (जानसठ)", "Shahpur (शाहपुर)", "Purkazi (पुरकाजी)", "Charthawal (चरथावल)", "Baghra (बाघरा)"],
    "Shamli (शामली)": ["Kairana (कैराना)", "Thana Bhawan (थाना भवन)", "Kandhla (कांधला)", "Un (ऊन)", "Garhi Pukhta (गढ़ी पुख्ता)", "Jalalabad (जलालाबाद)"],
    "Saharanpur (सहारनपुर)": ["Deoband (देवबंद)", "Nakur (नकुड़)", "Behat (बेहट)", "Rampur Maniharan (रामपुर मनिहारान)", "Gangoh (गंगोह)", "Nanauta (नानौता)", "Sarsawa (सरसावा)"],
    "Aligarh (अलीगढ़)": ["Atrauli (अतरौली)", "Iglas (इगलास)", "Khair (खैर)", "Gabhana (गभाना)", "Koil (कोल)", "Chandaus (चंडौस)", "Jawan Sikandarpur (जवां सिकंदरपुर)"],
    "Hathras (हाथरस)": ["Sadabad (सादाबाद)", "Sasni (सासनी)", "Sikandra Rao (सिकंदरा राव)", "Mursan (मुरसान)", "Sahpau (सहपऊ)", "Hasayan (हसायन)"],
    "Mathura (मथुरा)": ["Vrindavan (वृंदावन)", "Govardhan (गोवर्धन)", "Chhata (छाता)", "Mant (मांट)", "Barsana (बरसाना)", "Nandgaon (नंदगांव)", "Baldeo (बलदेव)", "Raya (राया)", "Farah (फरह)"],
    "Agra (आगरा)": ["Fatehabad (फतेहाबाद)", "Kiraoli (किरावली)", "Bah (बाह)", "Kheragarh (खेरागढ़)", "Etmadpur (एत्मादपुर)", "Bichpuri (बिचpuri)", "Achhnera (अछनेरा)", "Fatehpur Sikri (फतेहपुर सीकरी)", "Shamsabad (शमसाबाद)"],
    "Firozabad (फिरोजाबाद)": ["Shikohabad (शिकोहाबाद)", "Tundla (टूंडला)", "Jasrana (जसराना)", "Sirsaganj (सिरसागंज)", "Narkhi (नारखी)", "Araon (अरांव)"],
    "Mainpuri (मैनपुरी)": ["Bhongaon (भोगांव)", "Karhal (करहल)", "Kishni (किशनी)", "Kurawali (कुरावली)", "Ghiror (घिरोर)", "Bewar (बेवर)"],
    "Etah (एटा)": ["Aliganj (अलीगंज)", "Jalesar (जलेसर)", "Sakit (सकीट)", "Nidhauli Kalan (निधौली कलां)", "Jaithara (जैथरा)", "Marhara (मारहरा)"],
    "Kasganj (कासगंज)": ["Ganjdundwara (गंजडुंडवारा)", "Patiali (पटियाली)", "Sahawar (सहावर)", "Soron (सोरों)", "Sidhpura (सिढ़पुरा)"],
    "Budaun (बदायूं)": ["Bisauli (बिसौली)", "Sahaswan (सहसवान)", "Dataganj (दातागंज)", "Bilsi (बिल्सी)", "Gunnaur (गुन्नौर)", "Islamnagar (इस्लामनगर)", "Ujhani (उझानी)"],
    "Bareilly (बरेली)": ["Aonla (आंवला)", "Faridpur (फरीदपुर)", "Nawabganj (नवाबगंज)", "Baheri (बहेड़ी)", "Mirganj (मीरगंज)", "Bhojipura (भोजीपुरा)", "Fatehganj (फतेहगंज)"],
    "Pilibhit (पीलीभीत)": ["Puranpur (पूरनपुर)", "Bisalpur (बीसलपुर)", "Barkhera (बरखेड़ा)", "Amaria (अमरिया)", "Bilsanda (बिलसंडा)", "Majhola (मझोला)"],
    "Shahjahanpur (शाहजहांपुर)": ["Tilhar (तिलहर)", "Powayan (पुवायां)", "Jalalabad (जलालाबाद)", "Kalan (कलां)", "Khutar (खुदागंज)", "Banda (बंडा)", "Madnapur (मदनापुर)"],
    "Lakhimpur Kheri (लखीमपुर खीरी)": ["Gola Gokaran Nath (गोला गोकर्णनाथ)", "Mohammadi (मोहम्मदी)", "Nighasan (निघासन)", "Palia Kalan (पलिया कलां)", "Dhaurahra (धौरहरा)", "Mitauli (मितौली)", "Behjam (बेहजम)"],
    "Sitapur (सीतापुर)": ["Biswan (बिसवां)", "Mahmoodabad (महमूदाबाद)", "Sidhauli (सिधौली)", "Laharpur (लहरपुर)", "Misrikh (मिश्रिख)", "Hargaon (हरगांव)", "Khairabad (खैराबाद)"],
    "Hardoi (हरदोई)": ["Sandila (संडीला)", "Shahabad (शाहाबाद)", "Bilgram (बिलग्राम)", "Sawayajpur (सवायजपुर)", "Mallawan (मल्लवां)", "Kachhauna (कछौना)", "Bawan (बावन)"],
    "Unnao (उन्नाव)": ["Safipur (सफीपुर)", "Purwa (पुरवा)", "Hasanganj (हसनगंज)", "Bighapur (बीघापुर)", "Bangarmau (बांगरमऊ)", "Nawabganj (नवाबगंज)", "Miyanganj (मियांगंज)"],
    "Lucknow (लखनऊ)": ["Bakshi Ka Talab (बख्शी का तालाब)", "Mohanlalganj (मोहनलालगंज)", "Sarojini Nagar (सरोजिनी नगर)", "Gosainganj (गोसाईं गंज)", "Kakori (काकोरी)", "Maliahabad (मलिहाबाद)", "Chinhat (चिनहट)", "Itaunja (इटौंजा)"],
    "Rae Bareli (रायबरेली)": ["Lalganj (लालगंज)", "Salon (सलोन)", "Dalmau (डलमऊ)", "Maharajganj (महाराजगंज)", "Unchahar (ऊंचाहार)", "Bachhrawan (बछरावां)", "Sareni (सरेनी)"],
    "Amethi (अमेठी)": ["Gauriganj (गौरीगंज)", "Musafirkhana (मुसाफिरखाना)", "Tiloi (तिलोई)", "Jagdishpur (जगदीशपुर)", "Shukla Bazar (शुक्ला बाज़ार)", "Bhadar (भादर)"],
    "Sultanpur (सुलतानपुर)": ["Kadipur (कादीपुर)", "Jaisinghpur (जयसिंहपुर)", "Lambhua (लंभुआ)", "Kurebhar (कुरेभार)", "Dhanpatganj (धनपतगंज)", "Motigarpur (मोतीगरपुर)"],
    "Pratapgarh (प्रतापगढ़)": ["Kunda (कुंडा)", "Lalganj (लालगंज)", "Patti (पट्टी)", "Raniganj (रानीगंज)", "Babaganj (बाबागंज)", "Kalakankar (कालाकांकर)", "Kohndaur (कोहंडौर)"],
    "Fatehpur (फतेहपुर)": ["Bindki (बिंदकी)", "Khaga (खागा)", "Haswa (हसवा)", "Bahua (बहुआ)", "Amauli (अमौली)", "Airayan (ऐरायां)", "Hathgam (हथगाम)"],
    "Kaushambi (कौशाम्बी)": ["Manjhanpur (मंझनपुर)", "Sirathu (सिराथू)", "Chail (चायल)", "Mooratganj (मूरतगंज)", "Kara (कड़ा)", "Sarsawan (सरसावां)"],
    "Prayagraj (प्रयागराज)": ["Phulpur (फूलपुर)", "Koraon (कोरांव)", "Handia (हंडिया)", "Meja (मेजा)", "Bara (बारा)", "Karchhana (करछना)", "Soraon (सोरांव)", "Shankargarh (शंकरगढ़)", "Mau Aima (मऊआइमा)", "Holagarh (होलागढ़)"],
    "Barabanki (बाराबंकी)": ["Nawabganj (नवाबगंज)", "Fatehpur (फतेहपुर)", "Ramsanehighat (रामनगर)", "Haidergarh (हैदरगढ़)", "Sirauli Gauspur (सिरौली गौसपुर)", "Zaidpur (जैदपुर)", "Dewa (देवा)"],
    "Ayodhya (अयोध्या)": ["Rudauli (रुदौली)", "Bikapur (बीकापुर)", "Sohawal (सोहावल)", "Milkipur (मिल्कीपुर)", "Tarun (तारुन)", "Mayabazar (मायाबाज़ार)", "Pura Bazar (पूरा बाज़ार)"],
    "Ambedkar Nagar (अम्बेडकर नगर)": ["Akbarpur (अकबरपुर)", "Tanda (टांडा)", "Jalalpur (जलालपुर)", "Alapur (आलापुर)", "Bhiti (भीटी)", "Katehari (कटेहरी)", "Baskhari (बसखारी)"],
    "Bahraich (बहराइच)": ["Nanpara (नानपारा)", "Mahasi (महसी)", "Kaiserganj (कैसरगंज)", "Mihinpurwa (मिहींपुरवा)", "Payagpur (पयागपुर)", "Risia (रिसिया)", "Jarwal (जरवल)"],
    "Shravasti (श्रावस्ती)": ["Bhinga (भिनगा)", "Ikauna (इकौना)", "Jamunaha (जमुनहा)", "Gilaula (गिलौला)", "Sirsiya (सिरसिया)"],
    "Balrampur (बलरामपुर)": ["Tulsipur (तुलसीपुर)", "Utraula (उतरौला)", "Gaisari (गैसड़ी)", "Pachperwa (पचपेड़वा)", "Rehra Bazar (रेहरा बाज़ार)", "Harraiya (हर्रैया)"],
    "Gonda (गोंडा)": ["Tarabganj (तरबगंज)", "Colonelganj (करनैलगंज)", "Mankapur (मनकापुर)", "Katra Bazar (कटरा बाज़ार)", "Nawabganj (नवाबगंज)", "Paraspur (परसपुर)", "Itiyathok (इटियाथोक)"],
    "Siddharthnagar (सिद्धार्थनगर)": ["Naugarh (नौगढ़)", "Bansi (बांसी)", "Itwa (इटवा)", "Shohratgarh (शोहरतगढ़)", "Domariyaganj (डुमरियागंज)", "Birdpur (बर्डपुर)", "Uska Bazar (उस्का बाज़ार)"],
    "Basti (बस्ती)": ["Harraiya (हर्रैया)", "Bhanpur (भानपुर)", "Rudhauli (रुधौली)", "Kaptanganj (कप्तानगंज)", "Vikram Jot (विक्रमजोत)", "Saltaua (सल्टौआ)", "Gaur (गौड़)"],
    "Sant Kabir Nagar (संत कबीर नगर)": ["Khalilabad (खलीलाबाद)", "Mehdawal (मेहदावल)", "Dhanghata (धनघटा)", "Semariyawan (सेमरियावां)", "Baghnagar (बाघनगर)", "Belhar (बेलहर)"],
    "Maharajganj (महराजगंज)": ["Nautanwa (नौतनवा)", "Nichlaul (निचलौल)", "Pharenda (फरेन्दा)", "Siswa Bazar (सिसवा बाज़ार)", "Ghughli (घुघली)", "Paniyara (पनियारा)"],
    "Gorakhpur (गोरखपुर)": ["Sahjanwa (सहजनवा)", "Bansgaon (बांसगांव)", "Campierganj (कैंपियरगंज)", "Pipraich (पिपराइच)", "Chauri Chaura (चौरी चौरा)", "Brahmpur (ब्रह्मपुर)", "Khajni (खजनी)", "Gola (गोला)", "Barhalganj (बड़हलगंज)"],
    "Kushinagar (कुशीनगर)": ["Padrauna (पडरौना)", "Hata (हाटा)", "Tamkuhi Raj (तमकुही राज)", "Kasia (कसिया)", "Fazilnagar (फाजिलनगर)", "Kaptanganj (कप्तानगंज)", "Khadda (खड्डा)", "Ramkola (रामकोला)"],
    "Deoria (देवरिया)": ["Salempur (सलेमपुर)", "Rudrapur (रुद्रपुर)", "Bhatpar Rani (भाटपार रानी)", "Barhaj (बरहज)", "Gauri Bazar (गौरी बाज़ार)", "Lar (लार)", "Tarkulwa (तरकुलवा)", "Bhathahi (भटही)"],
    "Azamgarh (आजमगढ़)": ["Phulpur Pawai (फूलपुर पवई)", "Sagri (सगड़ी)", "Lalganj (लालगंज)", "Mehnagar (मेहनाजपुर)", "Nizamabad (निजामाबाद)", "Martinganj (मार्टीनगंज)", "Atraulia (अतरौलिया)", "Bilariyaganj (बिलरियागंज)", "Didarganj (दीदारगंज)"],
    "Mau (मऊ)": ["Ghosi (घोसी)", "Madhuban (मधुबन)", "Muhammadabad Gohna (मुहम्मदाबाद गोहना)", "Kopaganj (कोपागंज)", "Ranipur (रानीपुर)", "Ratanpura (रतनपुरा)", "Dohrighat (दोहरीघाट)"],
    "Ballia (बलिया)": ["Rasra (रसड़ा)", "Bansdih (बांसडीह)", "Bairia (बैरिया)", "Sikanderpur (सिकंदरपुर)", "Belthara Road (बेल्थरा रोड)", "Maniyar (मनियर)", "Reoti (रेवती)", "Chitbaragaon (चितबड़ागांव)"],
    "Jaunpur (जौनपुर)": ["Shahganj (शाहगंज)", "Machhlishahr (मछलीशहर)", "Badlapur (बदलापुर)", "Mariahu (मड़ियाहूं)", "Kerakat (केराकत)", "Barsathi (बरसठी)", "Khutahan (खुटाहन)", "Suitha Kala (सुईथाकला)"],
    "Ghazipur (गाजीपुर)": ["Zamania (जमानिया)", "Mohammadabad (मुहम्मदाबाद)", "Saidpur (सैदपुर)", "Jakhanian (जखनियां)", "Dildarnagar (दिलदारनगर)", "Bahadurganj (बहादुरगंज)", "Sadat (सादात)", "Karanda (करंडा)"],
    "Chandauli (चंदौली)": ["Mughalsarai / DDU Nagar (मुगलसराय)", "Sakaldiha (सकलडीहा)", "Chakia (चकिया)", "Naugarh (नौगढ़)", "Chandauli (चंदौली)", "Niamatabad (नियामताबाद)", "Dhanapur (धानापुर)"],
    "Varanasi (वाराणसी)": ["Pindra (पिंडरा)", "Cholapur (चोलापुर)", "Kashi Vidyapeeth (काशी विद्यापीठ)", "Arajiline (आराजीलाइन)", "Sevapuri (सेवापुरी)", "Harahua (हरहुआ)", "Rohaniya (रोहनिया)", "Shivpur (शिवपुर)", "Ramnagar (रामनगर)"],
    "Bhadohi (भदोही)": ["Gyanpur (ज्ञानपुर)", "Aurai (औराई)", "Suriyawan (सुरियावां)", "Deegh (दीघ)", "Abholi (अभोली)", "Gopiganj (गोपीगंज)"],
    "Mirzapur (मिर्जापुर)": ["Chunar (चुनार)", "Lalganj (लालगंज)", "Marihan (मड़िहान)", "Majhawa (मझवां)", "Kachhwa (कछवां)", "Guru Kripa (गुरू कृपा)", "Pahari (पहाड़ी)", "Halia (हलिया)"],
    "Sonbhadra (सोनभद्र)": ["Robertsganj (रॉबर्ट्सगंज)", "Duddhi (दुद्धी)", "Ghorawal (घोरावल)", "Obra (ओबरा)", "Renukoot (रेनुकूट)", "Anpara (अनपरा)", "Chopan (चोपन)", "Myorpur (म्योरपुर)"],
    "Jhansi (झांसी)": ["Mauranipur (मऊरानीपुर)", "Moth (मोठ)", "Garautha (गरौठा)", "Babina (बबीना)", "Bada Gaon (बड़ागांव)", "Chirgaon (चिरगांव)", "Gursarai (गुरसराय)"],
    "Lalitpur (ललितपुर)": ["Mahroni (महरौनी)", "Talbehat (तालबेहट)", "Madawara (मड़ावरा)", "Birdha (बिरधा)", "Bar (बार)", "Jakhaura (जखौरा)"],
    "Jalaun (जालौन)": ["Orai (उरई)", "Konch (कोंच)", "Kalpi (कालपी)", "Madhogarh (माधौगढ़)", "Kadaura (कदौरा)", "Nadigaon (नदीगांव)", "Rampura (रामपुरा)"],
    "Hamirpur (हमीरपुर)": ["Rath (राठ)", "Maudaha (मौदहा)", "Sumerpur (सुमेरपुर)", "Muskara (मुस्करा)", "Gohand (गोहंड)", "Sarila (सरीला)", "Kurara (कुरारा)"],
    "Mahoba (महोबा)": ["Charkhari (चरखारी)", "Kulpahar (कुलपहाड़)", "Kabrai (कबरई)", "Panwari (पनवाड़ी)", "Jaitpur (जैतपुर)", "Kharela (खरेला)"],
    "Banda (बांदा)": ["Atarra (अतर्रा)", "Baberu (बबेरू)", "Naraini (नरैनी)", "Tindwari (तिंदवारी)", "Bisanda (बिसंडा)", "Kamasin (कमासिन)", "Jaspura (जसपुरा)"],
    "Chitrakoot (चित्रकूट)": ["Karwi (कर्वी)", "Mau (मऊ)", "Manikpur (मानिकपुर)", "Rajapur (राजापुर)", "Pahari (पहाड़ी)", "Ramnagar (रामनगर)", "Bargarh (बरगढ़)"],
    "Kanpur Nagar (कानपुर नगर)": ["Bilhaur (बिल्हौर)", "Ghatampur (घाटमपुर)", "Bidhnu (बिधनू)", "Kalyanpur (कल्याणपुर)", "Sarsaul (सरसौल)", "Chaubepur (चौबेपुर)", "Shivrajpur (शिवराजपुर)", "Kakwan (ककवन)"],
    "Kanpur Dehat (कानपुर देहात)": ["Akbarpur (अकबरपुर)", "Bhognipur (भोगनीपुर)", "Rasulabad (रसूलाबाद)", "Derapur (डेरापुर)", "Sikandra (सिकंदरा)", "Maitha (मैथा)", "Amrutpur (अमृतपुर)", "Sandh (सांढ़)"],
    "Auraiya (औरैया)": ["Bidhuna (बिधूना)", "Ajeetmal (अजीतमल)", "Achhalda (अछल्दा)", "Bhagyanagar (भाग्यनगर)", "Sahar (सहार)", "Erwa Katra (एरवा कटरा)"],
    "Etawah (इटावा)": ["Saifai (सैफई)", "Jaswantnagar (जसवंतनगर)", "Bharthana (भरथना)", "Chakarnagar (चकरनगर)", "Basrehar (बसरेहर)", "Mahewa (महेवा)", "Takha (ताखा)"],
    "Farrukhabad (फर्रुखाबाद)": ["Fatehgarh (फतेहगढ़)", "Kaimganj (कायमगंज)", "Amritpur (अमृतपुर)", "Mohammadabad (मुहम्मदाबाद)", "Kamalganj (कमलगंज)", "Nawabganj (नवाबगंज)", "Shamsabad (शमसाबाद)"],
    "Kannauj (कन्नौज)": ["Chhibramau (छिबरामऊ)", "Tirwa (तिर्वा)", "Gursahaiganj (गुरसहायगंज)", "Talgram (तालग्राम)", "Jalalabad (जलालाबाद)", "Haseran (हसेरन)", "Saurikh (सौरिख)"],
    "Moradabad (मुरादाबाद)": ["Kanth (कांठ)", "Bilari (बिलारी)", "Thakurdwara (ठाकुरद्वारा)", "Kundarki (कुंदरकी)", "Dingarpur (डिंगरपुर)", "Bhagatpur (भगतपुर)", "Munda Pandey (मूढापांडे)"],
    "Rampur (रामपुर)": ["Bilaspur (बिलासपुर)", "Milak (मिलक)", "Shahabad (शाहाबाद)", "Suar (स्वार)", "Tanda (टांडा)", "Chamraua (चमराउआ)", "Saidnagar (सैदनगर)"],
    "Sambhal (संभल)": ["Chandausi (चंदौसी)", "Gunnaur (गुन्नौर)", "Bahjoi (बहजोई)", "Asmoli (असमौली)", "Pawansa (पवांसा)", "Rajpura (राजपुरा)", "Junawai (जुनावई)"],
    "Amroha (अमरोहा)": ["Hasanpur (हसनपुर)", "Dhanaura (धनौरा)", "Gajraula (गजरौला)", "Joya (जोया)", "Rehra (रेहरा)", "Naugawan Sadat (नौगावां सादात)"],
    "Bijnor (बिजनौर)": ["Chandpur (चांदपुर)", "Dhampur (धामपुर)", "Nagina (नगीना)", "Najibabad (नजीबाबाद)", "Noorpur (नूरपुर)", "Seohara (स्योहारा)", "Kiratpur (कीरतपुर)", "Haldaur (हल्दौर)", "Kotkadir (कोटकादिर)"]
  }
};

// Function to generate the master dataset
export function generateFullDataset() {
  return INDIA_DATA;
}
